# YOLOv8 Training Config
data: data/processed/dataset.yaml
epochs: 100
patience: 20
batch: 16
imgsz: 640
optimizer: AdamW
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
augment: true
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 10
translate: 0.1
scale: 0.5
shear: 2.0
flipud: 0.5
fliplr: 0.5
mosaic: 1.0
mixup: 0.1
project: models
name: waste_yolov8n
exist_ok: true
device: 0
workers: 4
amp: true
verbose: true
plots: true
save: true
save_period: 10
